services:
  # Servicio de la aplicación Node.js
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=001
      - DB_NAME=pedidosDB
      - DB_PORT=3306
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=001
      - MYSQL_DATABASE=pedidosDB
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p001"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 60s
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge